# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:  pretty

# Setup
title: Umbra Virtual
tagline: ''
description: "Olá, sou Roney. Aqui é um espaço onde escrevo sobre sobre software,
              computadores e possivelmente outras coisas menos irrelevantes."
baseurl: ''
paginate: 5

# About/contact
author:
  name: Roney Gomes
  email: roney477@gmail.com

# Custom vars
version: 1.0.0
