# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:  pretty

# Setup
title: Virtual Umbra
tagline: 'Virtual Umbra'
description: "Thoughts on software and work."
baseurl: ''
paginate: 5

# About/contact
author:
  name: Roney Gomes
  email: roney477@gmail.com

# Custom vars
version: 1.0.0
